* Adapting our results for the Carina proplyds
Tom and Leonardo Testi want my help in disentangling the ionization
front component to the [O I] emission from the disk  wind component

This is for application to measurements of YSOs in the Carina nebula
** What I need to do
- For the Orion proplyd sample, I should estimate what fraction of the
  [O I] emission comes from the ionization front
- I think I already have this - I seem to remember that I assumed that
  the Ha and [O I] profiles from the i-front were the same
- Yes, the assumption seems to have been that the profile of the ratio
  (proplyd / bg) is the same for Ha as for [O I]
  - [X] Look for an explicit statement of this in what I did
    - Yes, this is exactly what we did
    - In cases where the ionization front is clearly resolved, such as
      182-413, we can check this directly by looking at the two profiles
    - In general this seems to work, but there are some cases with discrepancies
      - In 182-413 the [O I] profile exceeds the Ha profile in most of
        the interior of the proplyd, but it could be argued that this
        is precisely because of the neutral disk wind, rather than the
        ionization front
      - In 168-326 (LV1) we see the complete opposite. The [O I] profile is
        weaker than the Ha profile pretty much everywhere.
        - In this case, it may be related to the high ratio [O I]/Ha
          in the BG, which is about 0.09, as opposed to 0.03 in more
          typical cases
        - Perhaps this is due to continuum in the 630n filter, or
          possibly [S III]
        - Others, such as 158-326 are similar, again with large [O
          I]/Ha ratio in the BG
      - Other cases have the [O I] and Ha tracking each opther
        approximately in the i-front part
        - examples are 177-341, 170-337, 180-331, 158-327, etc
  - So what are the relatives contribution of i-front and disk  wind
    to the total [O I] emission?
    - We will have to do this properly in the notebook, but just by
      eye we can see some clear variations:
      - One extreme is close-in proplyds such as 168-326, where the
        disk [O I] is essentially zero, so 100% comes from i-front
        - The same applies to many others with separation less than 10
          arcsec from th1c
      - Opposite extreme is case like 183-419 where Ha is very low, so
        i-front contribution  to [O I] is essentialy zero
      - More typical case is 177-341, where contribution of i-front is
        about 50%
      - There seems to be a clear trend with separation, but we need
        to run the notebook to see it - do  this tomorrow
*** Return to the notebook [2023-12-30 Sat]
- I have now rerun the notebook and modified to calculate the fraction of [O I] luminosity that comes from the neutral disk wind
- [[file:../notebooks/proplyd-pc-L-sep.pdf]]
- The fraction is low for separations less than 15 arcsec from Trapezium, but for farther out proplyds, it is more than 50 to 70%
*** TODO Convert from distance to G0
:LOGBOOK:
- State "TODO"       from              [2023-12-31 Sun 01:15] \\
  Do this tomorrow
:END:

**** Equations for G0
- From Henney & Arthur 2019, Bowshock Paper III
  - In Draine units: U = 14.7 L_4 / R_pc^2
  - Habing units depends on fraction of bolometric luminosity that is emitted in FUV band. For early O stars this is 0.4, giving G_0 = 6 U
  - So G_0 = 90 L_4 / R_pc^2

**** Values of G0 in Carina and Orion
- In Orion we have luminosity of th1C as 2e5 Lsun approx, but I need to get better value
  - 15 arcsec corresponds to a distance of 0.03 pc
  - So this means G_0 = 90 20 / 0.03**2 = 2e6
- Consistency check with Stoerzer & Hollenbach (1999)
  - G0 = 2e7 at 0.01 pc
  - G0 = 5e4 at 0.3 pc
  - so this implies G0 = 2000 / D_pc^2, which is within 10% of what I had before - close enough!
  - but we can combine with the current distance, so that 1 arcsec = 2 mpc
- The ionizing luminosity of Tr 14 is about 20 times Orion, so presumably the bolometric luminosity factor is similar
  - So G0 = 2e6 will occur at a radius that is sqrt(20) times larger, so 0.134 pc
  - But Carina is at 2350 pc, which is 5.66 times farther, so the angular separation is sqrt(20) / 5.66 = 0.79 times larger, so 12 arcsec
    - This is much smaller than typical radii of cluster stars in Tr 14
    - Even the core region is defined as 0.4 to 0.9 arcmin, so 24 to 54 arcsec, which is comfortably outside the high G0 regime
      - G0 = 8e5 to 1.5e5
    - The outer region goes out to 2 to 3 arcmin, so lowest values of G0 are about 2e4
** [2024-01-02 Tue] Message from Will
#+begin_quote
This is a plot of the fraction of the total [O I] 6300 emission that comes from the neutral disk wind as a function of G0 for the Orion proplyds (where the other fraction comes from the ionization front).  For G0 less than 2e7, this is consistent with a constant fraction of about 0.6 +/- 0.1.

Symbol size is proportional to size of ionization front. Symbol color is proportional to size of disk. There is no evidence for any significant dependence on either of these.  For the strongest radiation fields (G0 > 2e7), there is evidence that the fraction is lower (the downward pointing arrows are upper limits). 

For Carina Tr 14, the mapping from angular separation to G0 is almost the same as in Orion (the higher luminosity compensates for the greater distance). So the high G0 regime corresponds to the inner 10 arcsec of the cluster, and is not relevant to the sources in your MUSE sample. So I think you can safely use 0.6 as the correction factor. For the outer part of the Tr 14 data (radii larger than 1.5 arcmin) you will be at lower values of G0 than are sampled by these Orion data. We might expect the fraction to eventually go up to unity at very low G0, when internal irradiation takes over
#+end_quote
** [2023-12-21 Thu] Message from Tom
#+begin_quote
Leonardo (cc’d) has spectroscopic data towards a large number of YSOs in Tr 14 (e.g. https://ui.adsabs.harvard.edu/abs/2023arXiv230914168I/abstract). One of the things that would be nice to try and do with the data is compare against the recent Ballabio + 2023 paper on [OI] 6300 that you helped us with. They can certainly get the line luminosity and may be able to get the accretion luminosity too for the L_OI/L_acc diagnostic.

However with this dataset you dont spatially resolve proplyds so its hard to separate the I-front and PDR emission. I was wondering if it might be possible to look at the ONC proplyds and compare the PDR and I-front OI contributions to provide some rough correction for the spatially unresolved data (e.g. are the PDR and I-front line luminosities similar). We would be looking for global trends in the data (e.g. as a function of G0) so a representative fraction of luminosity in the PDR should be ok across the overall population, even if you wouldn’t trust it looking at an individual source. Obviously if it varies wildly it might not still be viable.

Presumably this would be quite straightforward for you as you already have a script to calculate only the PDR component, so it’d just be a case of printing out the I-front component that you previously threw out. Would this be something you could take a look at for us?

#+end_quote
